### ISSUE TITLE
How do you use this module?

### ISSUE THREAD

**Issue by yaronguez** [Jetski5822/Contrib.ImportExport#3]
Hi, I apologize for posting such a beginner's question, but I'm trying to export blog posts from an Orchard website into a WordPress one.  I have zero Orchard experience and found and installed this module but I can't figure out how to actually use it.  Is there an admin screen somewhere that does the importing and exporting?

**Comment by Jetski5822** [comment]
Hi there, Are you looking to export your posts?

**Comment by yaronguez** [comment]
Yes.  I'm looking to export my blog posts from Orchard to WordPress self hosted.

**Comment by hsimah** [comment]
It seems the module doesn't work. I checked in Routes and it has one for ~/Admin/Blogs/Import but the Blog controller seems to want to find a blog with the id of Import, and fails.

**Comment by Jetski5822** [comment]
Oddness, maybe it doesnt work on 1.9, if I upgrade quickly, can you give it a test?

**Comment by hsimah** [comment]
Woah, that was fast. Yeah, I can test it for you.

**Comment by Jetski5822** [comment]
Coolness, give me 15 minutes!

**Comment by Jetski5822** [comment]
@hsimah okay, pushed a compiling build for 1.9 to the master branch.

**Comment by hsimah** [comment]
Works fine now. I see Import under Blog in the admin menu. (Sorry I didn't reply last night, I messed up my Orchard install trying to update it and it all got a bit too much for me.)

**Comment by Jetski5822** [comment]
@hsimah awesome!! :)
